---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - kubeinbox.io.kubeinbox.io
  resources:
  - ec2costoptimizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubeinbox.io.kubeinbox.io
  resources:
  - ec2costoptimizers/finalizers
  verbs:
  - update
- apiGroups:
  - kubeinbox.io.kubeinbox.io
  resources:
  - ec2costoptimizers/status
  verbs:
  - get
  - patch
  - update
